#!/usr/bin/env ruby

require 'open-uri'
require 'nokogiri'
require 'optparse'

options = ARGV.getopts('n')

url = 'https://docs.google.com/spreadsheets/d/18s122iy_F8RgivDzF6BE6fL-nuHyOql5lZ3E_qeA1Dw/pubhtml?gid=1701793155&single=true'

charset = nil
html = open(url) do |f|
  charset = f.charset
  f.read
end

html = Nokogiri::HTML.parse(html, nil, charset).xpath('/html/body')

array = []
html.css('tbody tr').each do |tr|
  next if tr.css('td')[1].nil?

  no         = tr.css('td')[0].text
  date       = tr.css('td')[1].text
  author     = tr.css('td')[2].text
  page_title = tr.css('td')[3].text
  page_url   = tr.css('td')[4].text

  array << [no, date, author, page_title, page_url]
end

if options['n']
  array.each do |a|
    next if a[4].empty?

    puts a.join("\t")
  end
else
  array.each do |a|
    puts a.join("\t")
  end
end
